// 클래식 홀리 그레일 데이터 — 유니크 385 + 세트 부위 127 = 512.
// 출처: blizzhackers/d2data 공개 덤프(uniqueitems·setitems + localestrings-kor). 게임 string table이 정본이며
//       위키 번역·직역을 쓰지 않는다. koKR 표기가 없는 항목(= 3.x 신규)은 lib/items.js가 이미 보유하므로 제외.
// 필터: spawnable=1 (미사용·퀘스트 아이템 제외). 레인보우 패싯 8종은 이름·베이스가 같아 속성/발동으로 ID를 구분.
//
// ⚠ id는 여기 **명시된 값이 정본**이다. 체크 상태가 곧 id 문자열이므로 한 글자도 바꾸지 말 것 —
//   바꾸는 순간 사용자의 수집 체크가 증발한다.
//   안전망: test/grail-data.test.mjs 가 **682개 id 문자열 전수**를 test/grail-ids.snapshot.json 과 대조한다.
//   여기 id를 하나라도 고치면 그 테스트가 사라진 id를 이름으로 지목하며 실패한다(2026-07-16 망가뜨림 실험으로 확인).
//   ⚠ 2026-07-16 이전 이 자리의 "스냅샷으로 고정한다"는 **거짓이었다** — 당시 테스트는 개수·정규식만 봤고
//     날조 id가 EXIT 0으로 통과했다. 지금은 사실이나, **믿지 말고 직접 망가뜨려 확인하라.**

export const CLASSIC = [
  { id: "u:The Gnasher (Hand Axe)", kr: "더 내셔", en: "The Gnasher", cat: "unique", base: "Hand Axe" },
  { id: "u:Deathspade (Axe)", kr: "데쓰스페이드", en: "Deathspade", cat: "unique", base: "Axe" },
  { id: "u:Bladebone (Double Axe)", kr: "블레이드본", en: "Bladebone", cat: "unique", base: "Double Axe" },
  { id: "u:Mindrend (Military Pick)", kr: "스컬 스플리터", en: "Mindrend", cat: "unique", base: "Military Pick" },
  { id: "u:Rakescar (War Axe)", kr: "레이크스카", en: "Rakescar", cat: "unique", base: "War Axe" },
  { id: "u:Fechmars Axe (Large Axe)", kr: "액스 오브 페크마", en: "Fechmars Axe", cat: "unique", base: "Large Axe" },
  { id: "u:Goreshovel (Broad Axe)", kr: "고어셔벌", en: "Goreshovel", cat: "unique", base: "Broad Axe" },
  { id: "u:The Chieftan (Battle Axe)", kr: "더 치프턴", en: "The Chieftan", cat: "unique", base: "Battle Axe" },
  { id: "u:Brainhew (Great Axe)", kr: "브레인휴", en: "Brainhew", cat: "unique", base: "Great Axe" },
  { id: "u:The Humongous (Giant Axe)", kr: "휴멍거스", en: "The Humongous", cat: "unique", base: "Giant Axe" },
  { id: "u:Iros Torch (Wand)", kr: "토치 오브 이로", en: "Iros Torch", cat: "unique", base: "Wand" },
  { id: "u:Maelstromwrath (Yew Wand)", kr: "메일스트럼", en: "Maelstromwrath", cat: "unique", base: "Yew Wand" },
  { id: "u:Gravenspine (Bone Wand)", kr: "그레이븐스파인", en: "Gravenspine", cat: "unique", base: "Bone Wand" },
  { id: "u:Umes Lament (Grim Wand)", kr: "우메즈 러먼트", en: "Umes Lament", cat: "unique", base: "Grim Wand" },
  { id: "u:Felloak (Club)", kr: "펠오크", en: "Felloak", cat: "unique", base: "Club" },
  { id: "u:Knell Striker (Scepter)", kr: "넬 스트라이커", en: "Knell Striker", cat: "unique", base: "Scepter" },
  { id: "u:Rusthandle (Grand Scepter)", kr: "러스트 핸들", en: "Rusthandle", cat: "unique", base: "Grand Scepter" },
  { id: "u:Stormeye (War Scepter)", kr: "스톰아이", en: "Stormeye", cat: "unique", base: "War Scepter" },
  { id: "u:Stoutnail (Spiked Club)", kr: "스타우트네일", en: "Stoutnail", cat: "unique", base: "Spiked Club" },
  { id: "u:Crushflange (Mace)", kr: "크러쉬플랜지", en: "Crushflange", cat: "unique", base: "Mace" },
  { id: "u:Bloodrise (Morning Star)", kr: "블러드라이즈", en: "Bloodrise", cat: "unique", base: "Morning Star" },
  { id: "u:The Generals Tan Do Li Ga (Flail)", kr: "치우천왕의 철퇴", en: "The Generals Tan Do Li Ga", cat: "unique", base: "Flail" },
  { id: "u:Ironstone (War Hammer)", kr: "아이언스톤", en: "Ironstone", cat: "unique", base: "War Hammer" },
  { id: "u:Bonesob (Maul)", kr: "본스냅", en: "Bonesob", cat: "unique", base: "Maul" },
  { id: "u:Steeldriver (Great Maul)", kr: "스틸드라이버", en: "Steeldriver", cat: "unique", base: "Great Maul" },
  { id: "u:Rixots Keen (Short Sword)", kr: "릭잣즈 킨", en: "Rixots Keen", cat: "unique", base: "Short Sword" },
  { id: "u:Blood Crescent (Scimitar)", kr: "블러드 크레센트", en: "Blood Crescent", cat: "unique", base: "Scimitar" },
  { id: "u:Krintizs Skewer (Saber)", kr: "스큐어 오브 크린티즈", en: "Krintizs Skewer", cat: "unique", base: "Saber" },
  { id: "u:Gleamscythe (Falchion)", kr: "글림싸이드", en: "Gleamscythe", cat: "unique", base: "Falchion" },
  { id: "u:Griswolds Edge (Broad Sword)", kr: "그리스월즈엣지", en: "Griswolds Edge", cat: "unique", base: "Broad Sword" },
  { id: "u:Hellplague (Long Sword)", kr: "헬플레이그", en: "Hellplague", cat: "unique", base: "Long Sword" },
  { id: "u:Culwens Point (War Sword)", kr: "컬웬즈 포인트", en: "Culwens Point", cat: "unique", base: "War Sword" },
  { id: "u:Shadowfang (2-Handed Sword)", kr: "쉐도우팽", en: "Shadowfang", cat: "unique", base: "2-Handed Sword" },
  { id: "u:Soulflay (Claymore)", kr: "소울플레이", en: "Soulflay", cat: "unique", base: "Claymore" },
  { id: "u:Kinemils Awl (Giant Sword)", kr: "키네밀즈 얼", en: "Kinemils Awl", cat: "unique", base: "Giant Sword" },
  { id: "u:Blacktongue (Bastard Sword)", kr: "블랙텅", en: "Blacktongue", cat: "unique", base: "Bastard Sword" },
  { id: "u:Ripsaw (Flamberge)", kr: "립서어", en: "Ripsaw", cat: "unique", base: "Flamberge" },
  { id: "u:The Patriarch (Great Sword)", kr: "더 페이트리악", en: "The Patriarch", cat: "unique", base: "Great Sword" },
  { id: "u:Gull (Dagger)", kr: "걸", en: "Gull", cat: "unique", base: "Dagger" },
  { id: "u:The Diggler (Dirk)", kr: "더 디글러", en: "The Diggler", cat: "unique", base: "Dirk" },
  { id: "u:The Jade Tan Do (Kris)", kr: "아사달의 단도", en: "The Jade Tan Do", cat: "unique", base: "Kris" },
  { id: "u:Irices Shard (Blade)", kr: "스펙트럴 샤드", en: "Irices Shard", cat: "unique", base: "Blade" },
  { id: "u:The Dragon Chang (Spear)", kr: "운사의 용봉창", en: "The Dragon Chang", cat: "unique", base: "Spear" },
  { id: "u:Razortine (Trident)", kr: "레이저타인", en: "Razortine", cat: "unique", base: "Trident" },
  { id: "u:Bloodthief (Brandistock)", kr: "블러드씨프", en: "Bloodthief", cat: "unique", base: "Brandistock" },
  { id: "u:Lance of Yaggai (Spetum)", kr: "랜스 오브 야가이", en: "Lance of Yaggai", cat: "unique", base: "Spetum" },
  { id: "u:The Tannr Gorerod (Pike)", kr: "더 탄르 고어라드", en: "The Tannr Gorerod", cat: "unique", base: "Pike" },
  { id: "u:Dimoaks Hew (Bardiche)", kr: "디모악스 휴", en: "Dimoaks Hew", cat: "unique", base: "Bardiche" },
  { id: "u:Steelgoad (Voulge)", kr: "스틸고드", en: "Steelgoad", cat: "unique", base: "Voulge" },
  { id: "u:Soul Harvest (Scythe)", kr: "소울 하베스트", en: "Soul Harvest", cat: "unique", base: "Scythe" },
  { id: "u:The Battlebranch (Poleaxe)", kr: "더 배틀브랜치", en: "The Battlebranch", cat: "unique", base: "Poleaxe" },
  { id: "u:Woestave (Halberd)", kr: "워스테이브", en: "Woestave", cat: "unique", base: "Halberd" },
  { id: "u:The Grim Reaper (War Scythe)", kr: "더 그림 리퍼", en: "The Grim Reaper", cat: "unique", base: "War Scythe" },
  { id: "u:Bane Ash (Short Staff)", kr: "베인 애쉬", en: "Bane Ash", cat: "unique", base: "Short Staff" },
  { id: "u:Serpent Lord (Long Staff)", kr: "서펀트 로드", en: "Serpent Lord", cat: "unique", base: "Long Staff" },
  { id: "u:Lazarus Spire (Gnarled Staff)", kr: "스파이어 오브 라자루스", en: "Lazarus Spire", cat: "unique", base: "Gnarled Staff" },
  { id: "u:The Salamander (Battle Staff)", kr: "더 샐러맨더", en: "The Salamander", cat: "unique", base: "Battle Staff" },
  { id: "u:The Iron Jang Bong (War Staff)", kr: "풍사의 철장봉", en: "The Iron Jang Bong", cat: "unique", base: "War Staff" },
  { id: "u:Pluckeye (Short Bow)", kr: "플럭아이", en: "Pluckeye", cat: "unique", base: "Short Bow" },
  { id: "u:Witherstring (Hunter\\92s Bow)", kr: "위더스트링", en: "Witherstring", cat: "unique", base: "Hunter\\92s Bow" },
  { id: "u:Rimeraven (Long Bow)", kr: "레이븐 클러", en: "Rimeraven", cat: "unique", base: "Long Bow" },
  { id: "u:Piercerib (Composite Bow)", kr: "로그스 보우", en: "Piercerib", cat: "unique", base: "Composite Bow" },
  { id: "u:Pullspite (Short Battle Bow)", kr: "스톰스트라이크", en: "Pullspite", cat: "unique", base: "Short Battle Bow" },
  { id: "u:Wizendraw (Long Battle Bow)", kr: "위즌드로우", en: "Wizendraw", cat: "unique", base: "Long Battle Bow" },
  { id: "u:Hellclap (Short War Bow)", kr: "헬캡", en: "Hellclap", cat: "unique", base: "Short War Bow" },
  { id: "u:Blastbark (Long War Bow)", kr: "블래스트바크", en: "Blastbark", cat: "unique", base: "Long War Bow" },
  { id: "u:Leadcrow (Light Crossbow)", kr: "리드크로우", en: "Leadcrow", cat: "unique", base: "Light Crossbow" },
  { id: "u:Ichorsting (Crossbow)", kr: "아이커스팅", en: "Ichorsting", cat: "unique", base: "Crossbow" },
  { id: "u:Hellcast (Heavy Crossbow)", kr: "헬캐스트", en: "Hellcast", cat: "unique", base: "Heavy Crossbow" },
  { id: "u:Doomspittle (Repeating Crossbow)", kr: "둠슬링어", en: "Doomspittle", cat: "unique", base: "Repeating Crossbow" },
  { id: "u:War Bonnet (Cap)", kr: "비긴즈 보넷", en: "War Bonnet", cat: "unique", base: "Cap" },
  { id: "u:Tarnhelm (Skull Cap)", kr: "탄헬름", en: "Tarnhelm", cat: "unique", base: "Skull Cap" },
  { id: "u:Coif of Glory (Helm)", kr: "커이프 오브 글로리", en: "Coif of Glory", cat: "unique", base: "Helm" },
  { id: "u:Duskdeep (Full Helm)", kr: "더스크디프", en: "Duskdeep", cat: "unique", base: "Full Helm" },
  { id: "u:Wormskull (Bone Helm)", kr: "웜스컬", en: "Wormskull", cat: "unique", base: "Bone Helm" },
  { id: "u:Howltusk (Great Helm)", kr: "하울터스크", en: "Howltusk", cat: "unique", base: "Great Helm" },
  { id: "u:Undead Crown (Crown)", kr: "언데드 크라운", en: "Undead Crown", cat: "unique", base: "Crown" },
  { id: "u:The Face of Horror (Mask)", kr: "더 페이스 오브 호러", en: "The Face of Horror", cat: "unique", base: "Mask" },
  { id: "u:Greyform (Quilted Armor)", kr: "글레이폼", en: "Greyform", cat: "unique", base: "Quilted Armor" },
  { id: "u:Blinkbats Form (Leather Armor)", kr: "블링크뱃스 폼", en: "Blinkbats Form", cat: "unique", base: "Leather Armor" },
  { id: "u:The Centurion (Hard Leather)", kr: "더 센츄리언", en: "The Centurion", cat: "unique", base: "Hard Leather" },
  { id: "u:Twitchthroe (Studded Leather)", kr: "트윗치쓰로", en: "Twitchthroe", cat: "unique", base: "Studded Leather" },
  { id: "u:Darkglow (Ring Mail)", kr: "다크글로우", en: "Darkglow", cat: "unique", base: "Ring Mail" },
  { id: "u:Hawkmail (Scale Mail)", kr: "호크메일", en: "Hawkmail", cat: "unique", base: "Scale Mail" },
  { id: "u:Sparking Mail (Chain Mail)", kr: "스파킹 메일", en: "Sparking Mail", cat: "unique", base: "Chain Mail" },
  { id: "u:Venomsward (Breast Plate)", kr: "베넘 워드", en: "Venomsward", cat: "unique", base: "Breast Plate" },
  { id: "u:Iceblink (Splint Mail)", kr: "아이스블링크", en: "Iceblink", cat: "unique", base: "Splint Mail" },
  { id: "u:Boneflesh (Plate Mail)", kr: "본플레쉬", en: "Boneflesh", cat: "unique", base: "Plate Mail" },
  { id: "u:Rockfleece (Field Plate)", kr: "락플리스", en: "Rockfleece", cat: "unique", base: "Field Plate" },
  { id: "u:Rattlecage (Gothic Plate)", kr: "래틀케이지", en: "Rattlecage", cat: "unique", base: "Gothic Plate" },
  { id: "u:Goldskin (Full Plate Mail)", kr: "골드스킨", en: "Goldskin", cat: "unique", base: "Full Plate Mail" },
  { id: "u:Victors Silk (AncientArmor)", kr: "실크 오브 빅터", en: "Victors Silk", cat: "unique", base: "AncientArmor" },
  { id: "u:Heavenly Garb (Light Plate)", kr: "헤븐리 가브", en: "Heavenly Garb", cat: "unique", base: "Light Plate" },
  { id: "u:Pelta Lunata (Buckler)", kr: "펠타 루나타", en: "Pelta Lunata", cat: "unique", base: "Buckler" },
  { id: "u:Umbral Disk (Small Shield)", kr: "엄브럴 디스크", en: "Umbral Disk", cat: "unique", base: "Small Shield" },
  { id: "u:Stormguild (Large Shield)", kr: "스톰길드", en: "Stormguild", cat: "unique", base: "Large Shield" },
  { id: "u:Wall of the Eyeless (Bone Shield)", kr: "월 오브 디 아이리스", en: "Wall of the Eyeless", cat: "unique", base: "Bone Shield" },
  { id: "u:Swordback Hold (Spiked Shield)", kr: "소드백 홀드", en: "Swordback Hold", cat: "unique", base: "Spiked Shield" },
  { id: "u:Steelclash (Kite Shield)", kr: "스틸클래쉬", en: "Steelclash", cat: "unique", base: "Kite Shield" },
  { id: "u:Bverrit Keep (Tower Shield)", kr: "브베리트 킵", en: "Bverrit Keep", cat: "unique", base: "Tower Shield" },
  { id: "u:The Ward (Gothic Shield)", kr: "더 워드", en: "The Ward", cat: "unique", base: "Gothic Shield" },
  { id: "u:The Hand of Broc (Gloves)", kr: "더 헨드 오브 브록", en: "The Hand of Broc", cat: "unique", base: "Gloves" },
  { id: "u:Bloodfist (Heavy Gloves)", kr: "블러드피스트", en: "Bloodfist", cat: "unique", base: "Heavy Gloves" },
  { id: "u:Chance Guards (Bracers)", kr: "챈스 가드", en: "Chance Guards", cat: "unique", base: "Bracers" },
  { id: "u:Magefist (Light Gauntlets)", kr: "메이지피스트", en: "Magefist", cat: "unique", base: "Light Gauntlets" },
  { id: "u:Frostburn (Gauntlets)", kr: "프로스트번", en: "Frostburn", cat: "unique", base: "Gauntlets" },
  { id: "u:Hotspur (Leather Boots)", kr: "핫스퍼", en: "Hotspur", cat: "unique", base: "Leather Boots" },
  { id: "u:Gorefoot (Heavy Boots)", kr: "고어풋", en: "Gorefoot", cat: "unique", base: "Heavy Boots" },
  { id: "u:Treads of Cthon (Chain Boots)", kr: "트레츠 오브 크던", en: "Treads of Cthon", cat: "unique", base: "Chain Boots" },
  { id: "u:Goblin Toe (Light Plate Boots)", kr: "고블린 토우", en: "Goblin Toe", cat: "unique", base: "Light Plate Boots" },
  { id: "u:Tearhaunch (Plate Boots)", kr: "티어헌치", en: "Tearhaunch", cat: "unique", base: "Plate Boots" },
  { id: "u:Lenyms Cord (Sash)", kr: "레니모", en: "Lenyms Cord", cat: "unique", base: "Sash" },
  { id: "u:Snakecord (Light Belt)", kr: "스네이크코드", en: "Snakecord", cat: "unique", base: "Light Belt" },
  { id: "u:Nightsmoke (Belt)", kr: "나이트스모크", en: "Nightsmoke", cat: "unique", base: "Belt" },
  { id: "u:Goldwrap (Heavy Belt)", kr: "골드랩", en: "Goldwrap", cat: "unique", base: "Heavy Belt" },
  { id: "u:Bladebuckle (Girdle)", kr: "브레이드버클", en: "Bladebuckle", cat: "unique", base: "Girdle" },
  { id: "u:Nokozan Relic (Amulet)", kr: "노코잔 렐릭", en: "Nokozan Relic", cat: "unique", base: "Amulet" },
  { id: "u:The Eye of Etlich (Amulet)", kr: "더 아이 오브 에틀릭", en: "The Eye of Etlich", cat: "unique", base: "Amulet" },
  { id: "u:The Mahim-Oak Curio (Amulet)", kr: "더 마힘 오크 큐리오우", en: "The Mahim-Oak Curio", cat: "unique", base: "Amulet" },
  { id: "u:Nagelring (Ring)", kr: "나겔링", en: "Nagelring", cat: "unique", base: "Ring" },
  { id: "u:Manald Heal (Ring)", kr: "머날드 힐", en: "Manald Heal", cat: "unique", base: "Ring" },
  { id: "u:The Stone of Jordan (Ring)", kr: "더 스톤 오브 조던", en: "The Stone of Jordan", cat: "unique", base: "Ring" },
  { id: "u:Amulet of the Viper (Amulet)", kr: "아뮬렛 오브 더 바이퍼", en: "Amulet of the Viper", cat: "unique", base: "Amulet" },
  { id: "u:Staff of Kings (Staff)", kr: "스태프 오브 킹스", en: "Staff of Kings", cat: "unique", base: "Staff" },
  { id: "u:Horadric Staff (Staff)", kr: "호라드릭 스태프", en: "Horadric Staff", cat: "unique", base: "Staff" },
  { id: "u:Hell Forge Hammer (Hammer)", kr: "헬 포지 해머", en: "Hell Forge Hammer", cat: "unique", base: "Hammer" },
  { id: "u:KhalimFlail (Flail)", kr: "칼림스 프레일", en: "KhalimFlail", cat: "unique", base: "Flail" },
  { id: "u:SuperKhalimFlail (Flail)", kr: "칼림스 윌", en: "SuperKhalimFlail", cat: "unique", base: "Flail" },
  { id: "u:Coldkill (Hatchet)", kr: "콜드킬", en: "Coldkill", cat: "unique", base: "Hatchet" },
  { id: "u:Butcher's Pupil (Cleaver)", kr: "부쳐의 퓨필", en: "Butcher's Pupil", cat: "unique", base: "Cleaver" },
  { id: "u:Islestrike (Twin Axe)", kr: "아일스트라이크", en: "Islestrike", cat: "unique", base: "Twin Axe" },
  { id: "u:Pompe's Wrath (Crowbill)", kr: "폼페이의 래쓰", en: "Pompe's Wrath", cat: "unique", base: "Crowbill" },
  { id: "u:Guardian Naga (Naga)", kr: "가디안 나가", en: "Guardian Naga", cat: "unique", base: "Naga" },
  { id: "u:Warlord's Trust (Military Axe)", kr: "워로드의 트러스트", en: "Warlord's Trust", cat: "unique", base: "Military Axe" },
  { id: "u:Spellsteel (Bearded Axe)", kr: "스펠스틸", en: "Spellsteel", cat: "unique", base: "Bearded Axe" },
  { id: "u:Stormrider (Tabar)", kr: "스톰라이더", en: "Stormrider", cat: "unique", base: "Tabar" },
  { id: "u:Boneslayer Blade (Gothic Axe)", kr: "본슬레이어 블레이드", en: "Boneslayer Blade", cat: "unique", base: "Gothic Axe" },
  { id: "u:The Minataur (Ancient Axe)", kr: "미노타우로스", en: "The Minataur", cat: "unique", base: "Ancient Axe" },
  { id: "u:Suicide Branch (Burnt Wand)", kr: "수어사이드 브랜치", en: "Suicide Branch", cat: "unique", base: "Burnt Wand" },
  { id: "u:Carin Shard (Petrified Wand)", kr: "캐린 샤드", en: "Carin Shard", cat: "unique", base: "Petrified Wand" },
  { id: "u:Arm of King Leoric (Tomb Wand)", kr: "암 오브 킹 로릭", en: "Arm of King Leoric", cat: "unique", base: "Tomb Wand" },
  { id: "u:Blackhand Key (Grave Wand)", kr: "블랙핸드 키", en: "Blackhand Key", cat: "unique", base: "Grave Wand" },
  { id: "u:Dark Clan Crusher (Cudgel)", kr: "다크 클랜 크러셔", en: "Dark Clan Crusher", cat: "unique", base: "Cudgel" },
  { id: "u:Zakarum's Hand (Rune Scepter)", kr: "자카럼의 핸드", en: "Zakarum's Hand", cat: "unique", base: "Rune Scepter" },
  { id: "u:The Fetid Sprinkler (Holy Water Sprinkler)", kr: "페티드 스프링클러", en: "The Fetid Sprinkler", cat: "unique", base: "Holy Water Sprinkler" },
  { id: "u:Hand of Blessed Light (Divine Scepter)", kr: "핸드 오브 블레스드 라이트", en: "Hand of Blessed Light", cat: "unique", base: "Divine Scepter" },
  { id: "u:Fleshrender (Barbed Club)", kr: "플레쉬렌더", en: "Fleshrender", cat: "unique", base: "Barbed Club" },
  { id: "u:Sureshrill Frost (Flanged Mace)", kr: "수어쉬릴 프로스트", en: "Sureshrill Frost", cat: "unique", base: "Flanged Mace" },
  { id: "u:Moonfall (Jagged Star)", kr: "문폴", en: "Moonfall", cat: "unique", base: "Jagged Star" },
  { id: "u:Baezil's Vortex (Knout)", kr: "배질의 보어텍스", en: "Baezil's Vortex", cat: "unique", base: "Knout" },
  { id: "u:Earthshaker (Battle Hammer)", kr: "어스쉐이커", en: "Earthshaker", cat: "unique", base: "Battle Hammer" },
  { id: "u:Bloodtree Stump (War Club)", kr: "블러드트리 스텀프", en: "Bloodtree Stump", cat: "unique", base: "War Club" },
  { id: "u:The Gavel of Pain (Martel de Fer)", kr: "게벌 오브 페인", en: "The Gavel of Pain", cat: "unique", base: "Martel de Fer" },
  { id: "u:Bloodletter (Gladius)", kr: "블러드레터", en: "Bloodletter", cat: "unique", base: "Gladius" },
  { id: "u:Coldsteel Eye (Cutlass)", kr: "콜드스틸 아이", en: "Coldsteel Eye", cat: "unique", base: "Cutlass" },
  { id: "u:Hexfire (Shamshir)", kr: "헥스파이어", en: "Hexfire", cat: "unique", base: "Shamshir" },
  { id: "u:Blade of Ali Baba (Tulwar)", kr: "블레이드 오브 알리바바", en: "Blade of Ali Baba", cat: "unique", base: "Tulwar" },
  { id: "u:Ginther's Rift (Dimensional Blade)", kr: "진저스 리프트", en: "Ginther's Rift", cat: "unique", base: "Dimensional Blade" },
  { id: "u:Headstriker (Battle Sword)", kr: "헤드스트라이커", en: "Headstriker", cat: "unique", base: "Battle Sword" },
  { id: "u:Plague Bearer (Rune Sword)", kr: "플레이그 베어러", en: "Plague Bearer", cat: "unique", base: "Rune Sword" },
  { id: "u:The Atlantian (Ancient Sword)", kr: "애틀랜티언", en: "The Atlantian", cat: "unique", base: "Ancient Sword" },
  { id: "u:Crainte Vomir (Espadon)", kr: "크래인트 보미르", en: "Crainte Vomir", cat: "unique", base: "Espadon" },
  { id: "u:Bing Sz Wang (Dacian Falx)", kr: "빙 쯔 왕", en: "Bing Sz Wang", cat: "unique", base: "Dacian Falx" },
  { id: "u:The Vile Husk (Tusk Sword)", kr: "바일 하스크", en: "The Vile Husk", cat: "unique", base: "Tusk Sword" },
  { id: "u:Cloudcrack (Gothic Sword)", kr: "클라우드크랙", en: "Cloudcrack", cat: "unique", base: "Gothic Sword" },
  { id: "u:Todesfaelle Flamme (Zweihander)", kr: "토즈팰러 플렘", en: "Todesfaelle Flamme", cat: "unique", base: "Zweihander" },
  { id: "u:Swordguard (Executioner Sword)", kr: "소드가드", en: "Swordguard", cat: "unique", base: "Executioner Sword" },
  { id: "u:Spineripper (Poignard)", kr: "스파인리퍼", en: "Spineripper", cat: "unique", base: "Poignard" },
  { id: "u:Heart Carver (Rondel)", kr: "하트 카버", en: "Heart Carver", cat: "unique", base: "Rondel" },
  { id: "u:Blackbog's Sharp (Cinquedeas)", kr: "블랙보그의 샤프", en: "Blackbog's Sharp", cat: "unique", base: "Cinquedeas" },
  { id: "u:Stormspike (Stilleto)", kr: "스톰스파이크", en: "Stormspike", cat: "unique", base: "Stilleto" },
  { id: "u:The Impaler (War Spear)", kr: "임페일러", en: "The Impaler", cat: "unique", base: "War Spear" },
  { id: "u:Kelpie Snare (Fuscina)", kr: "켈피 스네어", en: "Kelpie Snare", cat: "unique", base: "Fuscina" },
  { id: "u:Soulfeast Tine (War Fork)", kr: "소울피스트 타인", en: "Soulfeast Tine", cat: "unique", base: "War Fork" },
  { id: "u:Hone Sundan (Yari)", kr: "혼 선단", en: "Hone Sundan", cat: "unique", base: "Yari" },
  { id: "u:Spire of Honor (Lance)", kr: "스파이어 오브 아너", en: "Spire of Honor", cat: "unique", base: "Lance" },
  { id: "u:The Meat Scraper (Lochaber Axe)", kr: "미트 스크레이퍼", en: "The Meat Scraper", cat: "unique", base: "Lochaber Axe" },
  { id: "u:Blackleach Blade (Bill)", kr: "블랙리취 블레이드", en: "Blackleach Blade", cat: "unique", base: "Bill" },
  { id: "u:Athena's Wrath (Battle Scythe)", kr: "아테네의 래쓰", en: "Athena's Wrath", cat: "unique", base: "Battle Scythe" },
  { id: "u:Pierre Tombale Couant (Partizan)", kr: "피에르 톰 콘", en: "Pierre Tombale Couant", cat: "unique", base: "Partizan" },
  { id: "u:Husoldal Evo (Bec-de-Corbin)", kr: "휴솔달 에보", en: "Husoldal Evo", cat: "unique", base: "Bec-de-Corbin" },
  { id: "u:Grim's Burning Dead (Grim Scythe)", kr: "그림의 버닝 데드", en: "Grim's Burning Dead", cat: "unique", base: "Grim Scythe" },
  { id: "u:Razorswitch (Jo Stalf)", kr: "레이저스위치", en: "Razorswitch", cat: "unique", base: "Jo Stalf" },
  { id: "u:Ribcracker (Quarterstaff)", kr: "립크래커", en: "Ribcracker", cat: "unique", base: "Quarterstaff" },
  { id: "u:Chromatic Ire (Cedar Staff)", kr: "크로마틱 아이어", en: "Chromatic Ire", cat: "unique", base: "Cedar Staff" },
  { id: "u:Warpspear (Gothic Staff)", kr: "워프스피어", en: "Warpspear", cat: "unique", base: "Gothic Staff" },
  { id: "u:Skullcollector (Rune Staff)", kr: "스컬 콜렉터", en: "Skullcollector", cat: "unique", base: "Rune Staff" },
  { id: "u:Skystrike (Edge Bow)", kr: "스카이스트라이크", en: "Skystrike", cat: "unique", base: "Edge Bow" },
  { id: "u:Riphook (Razor Bow)", kr: "립후크", en: "Riphook", cat: "unique", base: "Razor Bow" },
  { id: "u:Kuko Shakaku (CedarBow)", kr: "쿠코 샤카쿠", en: "Kuko Shakaku", cat: "unique", base: "CedarBow" },
  { id: "u:Endlesshail (Double Bow)", kr: "앤드리스해일", en: "Endlesshail", cat: "unique", base: "Double Bow" },
  { id: "u:Whichwild String (Short Siege Bow)", kr: "윗치와일드 스트링", en: "Whichwild String", cat: "unique", base: "Short Siege Bow" },
  { id: "u:Cliffkiller (Long Siege Bow)", kr: "클리프킬러", en: "Cliffkiller", cat: "unique", base: "Long Siege Bow" },
  { id: "u:Magewrath (Rune Bow)", kr: "메이지래쓰", en: "Magewrath", cat: "unique", base: "Rune Bow" },
  { id: "u:Godstrike Arch (Gothic Bow)", kr: "골드스트라이크 아치", en: "Godstrike Arch", cat: "unique", base: "Gothic Bow" },
  { id: "u:Langer Briser (Arbalest)", kr: "랭거 브리저", en: "Langer Briser", cat: "unique", base: "Arbalest" },
  { id: "u:Pus Spiter (Siege Crossbow)", kr: "퍼스 스피터", en: "Pus Spiter", cat: "unique", base: "Siege Crossbow" },
  { id: "u:Buriza-Do Kyanon (Balista)", kr: "부리자-도 캬논", en: "Buriza-Do Kyanon", cat: "unique", base: "Balista" },
  { id: "u:Demon Machine (Chu-Ko-Nu)", kr: "데몬 머신", en: "Demon Machine", cat: "unique", base: "Chu-Ko-Nu" },
  { id: "u:Peasent Crown (War Hat)", kr: "페전트 크라운", en: "Peasent Crown", cat: "unique", base: "War Hat" },
  { id: "u:Rockstopper (Sallet)", kr: "록스토퍼", en: "Rockstopper", cat: "unique", base: "Sallet" },
  { id: "u:Stealskull (Casque)", kr: "스틸스컬", en: "Stealskull", cat: "unique", base: "Casque" },
  { id: "u:Darksight Helm (Basinet)", kr: "다크사이트 헬름", en: "Darksight Helm", cat: "unique", base: "Basinet" },
  { id: "u:Valkiry Wing (Winged Helm)", kr: "발키리 윙", en: "Valkiry Wing", cat: "unique", base: "Winged Helm" },
  { id: "u:Crown of Thieves (Grand Crown)", kr: "크라운 오브 디브스", en: "Crown of Thieves", cat: "unique", base: "Grand Crown" },
  { id: "u:Blackhorn's Face (Death Mask)", kr: "블랙혼의 페이스", en: "Blackhorn's Face", cat: "unique", base: "Death Mask" },
  { id: "u:Vampiregaze (Grim Helm)", kr: "뱀파이어 게이즈", en: "Vampiregaze", cat: "unique", base: "Grim Helm" },
  { id: "u:The Spirit Shroud (Ghost Armor)", kr: "스피리트 슈라우드", en: "The Spirit Shroud", cat: "unique", base: "Ghost Armor" },
  { id: "u:Skin of the Vipermagi (SerpentSkin Armor)", kr: "스킨 오브 바이퍼마이자이", en: "Skin of the Vipermagi", cat: "unique", base: "SerpentSkin Armor" },
  { id: "u:Skin of the Flayerd One (Demonhide Armor)", kr: "스킨 오브 플라이드 원", en: "Skin of the Flayerd One", cat: "unique", base: "Demonhide Armor" },
  { id: "u:Ironpelt (Tresllised Armor)", kr: "아이언 펠트", en: "Ironpelt", cat: "unique", base: "Tresllised Armor" },
  { id: "u:Spiritforge (Linked Mail)", kr: "스피리트 포지", en: "Spiritforge", cat: "unique", base: "Linked Mail" },
  { id: "u:Crow Caw (Tigulated Mail)", kr: "크로우 코우", en: "Crow Caw", cat: "unique", base: "Tigulated Mail" },
  { id: "u:Shaftstop (Mesh Armor)", kr: "샤프트스톱", en: "Shaftstop", cat: "unique", base: "Mesh Armor" },
  { id: "u:Duriel's Shell (Cuirass)", kr: "듀리엘의 쉘", en: "Duriel's Shell", cat: "unique", base: "Cuirass" },
  { id: "u:Skullder's Ire (Russet Armor)", kr: "스컬더의 아이어", en: "Skullder's Ire", cat: "unique", base: "Russet Armor" },
  { id: "u:Guardian Angel (Templar Coat)", kr: "가디안 엔젤", en: "Guardian Angel", cat: "unique", base: "Templar Coat" },
  { id: "u:Toothrow (Sharktooth Armor)", kr: "투쓰로", en: "Toothrow", cat: "unique", base: "Sharktooth Armor" },
  { id: "u:Atma's Wail (Embossed Plate)", kr: "아트마의 와일", en: "Atma's Wail", cat: "unique", base: "Embossed Plate" },
  { id: "u:Black Hades (Chaos Armor)", kr: "블랙 하이드스", en: "Black Hades", cat: "unique", base: "Chaos Armor" },
  { id: "u:Corpsemourn (Ornate Armor)", kr: "커프스모온", en: "Corpsemourn", cat: "unique", base: "Ornate Armor" },
  { id: "u:Que-Hegan's Wisdon (Mage Plate)", kr: "퀘-히간의 위즈덤", en: "Que-Hegan's Wisdon", cat: "unique", base: "Mage Plate" },
  { id: "u:Visceratuant (Defender)", kr: "비서러턴트", en: "Visceratuant", cat: "unique", base: "Defender" },
  { id: "u:Mosers Blessed Circle (Round Shield)", kr: "모세의 블레스드 서클", en: "Mosers Blessed Circle", cat: "unique", base: "Round Shield" },
  { id: "u:Stormchaser (Scutum)", kr: "스톰체이서", en: "Stormchaser", cat: "unique", base: "Scutum" },
  { id: "u:Tiamat's Rebuke (Dragon Shield)", kr: "티아마트의 리뷰크", en: "Tiamat's Rebuke", cat: "unique", base: "Dragon Shield" },
  { id: "u:Kerke's Sanctuary (Pavise)", kr: "게르크의 생츄어리", en: "Kerke's Sanctuary", cat: "unique", base: "Pavise" },
  { id: "u:Radimant's Sphere (Ancient Shield)", kr: "라다만트의 스피어", en: "Radimant's Sphere", cat: "unique", base: "Ancient Shield" },
  { id: "u:Lidless Wall (Grim Shield)", kr: "리드리스 월", en: "Lidless Wall", cat: "unique", base: "Grim Shield" },
  { id: "u:Lance Guard (Barbed Shield)", kr: "랜스 가드", en: "Lance Guard", cat: "unique", base: "Barbed Shield" },
  { id: "u:Venom Grip (Demonhide Gloves)", kr: "베넘 그립", en: "Venom Grip", cat: "unique", base: "Demonhide Gloves" },
  { id: "u:Gravepalm (Sharkskin Gloves)", kr: "그레이브팜", en: "Gravepalm", cat: "unique", base: "Sharkskin Gloves" },
  { id: "u:Ghoulhide (Heavy Bracers)", kr: "구울하이드", en: "Ghoulhide", cat: "unique", base: "Heavy Bracers" },
  { id: "u:Lavagout (Battle Guantlets)", kr: "라바 가우트", en: "Lavagout", cat: "unique", base: "Battle Guantlets" },
  { id: "u:Hellmouth (War Gauntlets)", kr: "헬마우쓰", en: "Hellmouth", cat: "unique", base: "War Gauntlets" },
  { id: "u:Infernostride (Demonhide Boots)", kr: "인페르노스트라이드", en: "Infernostride", cat: "unique", base: "Demonhide Boots" },
  { id: "u:Waterwalk (Sharkskin Boots)", kr: "워터워크", en: "Waterwalk", cat: "unique", base: "Sharkskin Boots" },
  { id: "u:Silkweave (Mesh Boots)", kr: "실크위버", en: "Silkweave", cat: "unique", base: "Mesh Boots" },
  { id: "u:Wartraveler (Battle Boots)", kr: "워 트래블러", en: "Wartraveler", cat: "unique", base: "Battle Boots" },
  { id: "u:Gorerider (War Boots)", kr: "고어 라이더", en: "Gorerider", cat: "unique", base: "War Boots" },
  { id: "u:String of Ears (Demonhide Sash)", kr: "스트링 오브 이어스", en: "String of Ears", cat: "unique", base: "Demonhide Sash" },
  { id: "u:Razortail (Sharkskin Belt)", kr: "레이저테일", en: "Razortail", cat: "unique", base: "Sharkskin Belt" },
  { id: "u:Gloomstrap (Mesh Belt)", kr: "글룸스 트랩", en: "Gloomstrap", cat: "unique", base: "Mesh Belt" },
  { id: "u:Snowclash (Battle Belt)", kr: "스노우클래쉬", en: "Snowclash", cat: "unique", base: "Battle Belt" },
  { id: "u:Thudergod's Vigor (War Belt)", kr: "선더갓의 비거", en: "Thudergod's Vigor", cat: "unique", base: "War Belt" },
  { id: "u:Harlequin Crest (Shako)", kr: "할리퀸 크레스트", en: "Harlequin Crest", cat: "unique", base: "Shako" },
  { id: "u:Veil of Steel (Spired Helm)", kr: "베일 오브 스틸", en: "Veil of Steel", cat: "unique", base: "Spired Helm" },
  { id: "u:The Gladiator's Bane (Wire Fleece)", kr: "글래디에이터의 베인", en: "The Gladiator's Bane", cat: "unique", base: "Wire Fleece" },
  { id: "u:Arkaine's Valor (Balrog Skin)", kr: "아케인의 발러", en: "Arkaine's Valor", cat: "unique", base: "Balrog Skin" },
  { id: "u:Blackoak Shield (Luna)", kr: "블랙오크 쉴드", en: "Blackoak Shield", cat: "unique", base: "Luna" },
  { id: "u:Stormshield (Monarch)", kr: "스톰쉴드", en: "Stormshield", cat: "unique", base: "Monarch" },
  { id: "u:Hellslayer (Decapitator)", kr: "헬슬레이어", en: "Hellslayer", cat: "unique", base: "Decapitator" },
  { id: "u:Messerschmidt's Reaver (Champion Axe)", kr: "메서슈미트의 리버", en: "Messerschmidt's Reaver", cat: "unique", base: "Champion Axe" },
  { id: "u:Baranar's Star (Devil Star)", kr: "바라나의 별", en: "Baranar's Star", cat: "unique", base: "Devil Star" },
  { id: "u:Schaefer's Hammer (Legendary Mallet)", kr: "쉐퍼의 해머", en: "Schaefer's Hammer", cat: "unique", base: "Legendary Mallet" },
  { id: "u:The Cranium Basher (Thunder Maul)", kr: "크레이니엄 배셔", en: "The Cranium Basher", cat: "unique", base: "Thunder Maul" },
  { id: "u:Lightsabre (Phase Blade)", kr: "라이트세이버", en: "Lightsabre", cat: "unique", base: "Phase Blade" },
  { id: "u:Doombringer (Champion Sword)", kr: "둠브링거", en: "Doombringer", cat: "unique", base: "Champion Sword" },
  { id: "u:The Grandfather (Colossus Blade)", kr: "그랜드파더", en: "The Grandfather", cat: "unique", base: "Colossus Blade" },
  { id: "u:Wizardspike (Bone Knife)", kr: "위저드스파이크", en: "Wizardspike", cat: "unique", base: "Bone Knife" },
  { id: "u:Stormspire (Giant Thresher)", kr: "스톰스파이어", en: "Stormspire", cat: "unique", base: "Giant Thresher" },
  { id: "u:Eaglehorn (Crusader Bow)", kr: "이글혼", en: "Eaglehorn", cat: "unique", base: "Crusader Bow" },
  { id: "u:Windforce (Hydra Bow)", kr: "윈드포스", en: "Windforce", cat: "unique", base: "Hydra Bow" },
  { id: "u:Bul Katho's Wedding Band (Ring)", kr: "발카서스의 웨딩 밴드", en: "Bul Katho's Wedding Band", cat: "unique", base: "Ring" },
  { id: "u:The Cat's Eye (Amulet)", kr: "캐츠 아이", en: "The Cat's Eye", cat: "unique", base: "Amulet" },
  { id: "u:The Rising Sun (Amulet)", kr: "라이징 선", en: "The Rising Sun", cat: "unique", base: "Amulet" },
  { id: "u:Crescent Moon (Amulet)", kr: "초승달", en: "Crescent Moon", cat: "unique", base: "Amulet" },
  { id: "u:Mara's Kaleidoscope (Amulet)", kr: "마라의 컬라이더스코프", en: "Mara's Kaleidoscope", cat: "unique", base: "Amulet" },
  { id: "u:Atma's Scarab (Amulet)", kr: "아트마의 스캐럽", en: "Atma's Scarab", cat: "unique", base: "Amulet" },
  { id: "u:Dwarf Star (Ring)", kr: "드와프 스타", en: "Dwarf Star", cat: "unique", base: "Ring" },
  { id: "u:Raven Frost (Ring)", kr: "레이븐 프로스트", en: "Raven Frost", cat: "unique", base: "Ring" },
  { id: "u:Highlord's Wrath (Amulet)", kr: "하이로드의 래쓰", en: "Highlord's Wrath", cat: "unique", base: "Amulet" },
  { id: "u:Saracen's Chance (Amulet)", kr: "사라센의 찬스", en: "Saracen's Chance", cat: "unique", base: "Amulet" },
  { id: "u:Arreat's Face (Slayer Guard)", kr: "아리앗의 페이스", en: "Arreat's Face", cat: "unique", base: "Slayer Guard" },
  { id: "u:Homunculus (Heirophant Trophy)", kr: "호우먼컬러스", en: "Homunculus", cat: "unique", base: "Heirophant Trophy" },
  { id: "u:Titan's Revenge (Ceremonial Javelin)", kr: "타이탄의 리벤지", en: "Titan's Revenge", cat: "unique", base: "Ceremonial Javelin" },
  { id: "u:Lycander's Aim (Ceremonial Bow)", kr: "라이캔더의 에임", en: "Lycander's Aim", cat: "unique", base: "Ceremonial Bow" },
  { id: "u:Lycander's Flank (Ceremonial Pike)", kr: "라이캔더스 플랭크", en: "Lycander's Flank", cat: "unique", base: "Ceremonial Pike" },
  { id: "u:The Oculus (Swirling Crystal)", kr: "오큘러스", en: "The Oculus", cat: "unique", base: "Swirling Crystal" },
  { id: "u:Herald of Zakarum (Aerin Shield)", kr: "헤럴드 오브 자카럼", en: "Herald of Zakarum", cat: "unique", base: "Aerin Shield" },
  { id: "u:Cutthroat1 (Runic Talons)", kr: "바르턱스의 촙촙", en: "Cutthroat1", cat: "unique", base: "Runic Talons" },
  { id: "u:Jalal's Mane (Dream Spirit)", kr: "잘알의 메인", en: "Jalal's Mane", cat: "unique", base: "Dream Spirit" },
  { id: "u:The Scalper (Francisca)", kr: "스캘퍼", en: "The Scalper", cat: "unique", base: "Francisca" },
  { id: "u:Bloodmoon (elegant blade)", kr: "블러드문", en: "Bloodmoon", cat: "unique", base: "elegant blade" },
  { id: "u:Djinnslayer (ataghan)", kr: "진 슬레이어", en: "Djinnslayer", cat: "unique", base: "ataghan" },
  { id: "u:Deathbit (battle dart)", kr: "데쓰비트", en: "Deathbit", cat: "unique", base: "battle dart" },
  { id: "u:Warshrike (winged knife)", kr: "워슈라이크", en: "Warshrike", cat: "unique", base: "winged knife" },
  { id: "u:Gutsiphon (demon crossbow)", kr: "구트 쉬폰", en: "Gutsiphon", cat: "unique", base: "demon crossbow" },
  { id: "u:Razoredge (tomahawk)", kr: "레이저스 엣지", en: "Razoredge", cat: "unique", base: "tomahawk" },
  { id: "u:Demonlimb (tyrant club)", kr: "데몬 림", en: "Demonlimb", cat: "unique", base: "tyrant club" },
  { id: "u:Steelshade (armet)", kr: "스틸 쉐이드", en: "Steelshade", cat: "unique", base: "armet" },
  { id: "u:Tomb Reaver (cryptic axe)", kr: "툼 리버", en: "Tomb Reaver", cat: "unique", base: "cryptic axe" },
  { id: "u:Deaths's Web (unearthed wand)", kr: "데쓰 웹", en: "Deaths's Web", cat: "unique", base: "unearthed wand" },
  { id: "u:Nature's Peace (ring)", kr: "네이춰스 피스", en: "Nature's Peace", cat: "unique", base: "ring" },
  { id: "u:Azurewrath (phase blade)", kr: "에이져래쓰", en: "Azurewrath", cat: "unique", base: "phase blade" },
  { id: "u:Seraph's Hymn (amulet)", kr: "세라프의 힘", en: "Seraph's Hymn", cat: "unique", base: "amulet" },
  { id: "u:Fleshripper (fanged knife)", kr: "플레쉬리퍼", en: "Fleshripper", cat: "unique", base: "fanged knife" },
  { id: "u:Horizon's Tornado (scourge)", kr: "호라즌의 토네이도", en: "Horizon's Tornado", cat: "unique", base: "scourge" },
  { id: "u:Stone Crusher (legendary mallet)", kr: "스톤 크러셔", en: "Stone Crusher", cat: "unique", base: "legendary mallet" },
  { id: "u:Jadetalon (wrist sword)", kr: "제이드 탈런", en: "Jadetalon", cat: "unique", base: "wrist sword" },
  { id: "u:Shadowdancer (myrmidon greaves)", kr: "쉐도우 댄서", en: "Shadowdancer", cat: "unique", base: "myrmidon greaves" },
  { id: "u:Cerebus (blood spirit)", kr: "케레버스 바이트", en: "Cerebus", cat: "unique", base: "blood spirit" },
  { id: "u:Tyrael's Might (sacred armor)", kr: "티리얼의 마이트", en: "Tyrael's Might", cat: "unique", base: "sacred armor" },
  { id: "u:Souldrain (vambraces)", kr: "소울 드레이너", en: "Souldrain", cat: "unique", base: "vambraces" },
  { id: "u:Runemaster (ettin axe)", kr: "룬 마스터", en: "Runemaster", cat: "unique", base: "ettin axe" },
  { id: "u:Deathcleaver (berserker axe)", kr: "데쓰 클리버", en: "Deathcleaver", cat: "unique", base: "berserker axe" },
  { id: "u:Executioner's Justice (glorious axe)", kr: "엑시큐셔너의 저스티스", en: "Executioner's Justice", cat: "unique", base: "glorious axe" },
  { id: "u:Stoneraven (matriarchal spear)", kr: "스톤레이븐", en: "Stoneraven", cat: "unique", base: "matriarchal spear" },
  { id: "u:Leviathan (kraken shell)", kr: "레비아탄", en: "Leviathan", cat: "unique", base: "kraken shell" },
  { id: "u:Wisp (ring)", kr: "위스프 프로젝터", en: "Wisp", cat: "unique", base: "ring" },
  { id: "u:Gargoyle's Bite (winged harpoon)", kr: "가고일 바이트", en: "Gargoyle's Bite", cat: "unique", base: "winged harpoon" },
  { id: "u:Lacerator (winged axe)", kr: "래서레이트", en: "Lacerator", cat: "unique", base: "winged axe" },
  { id: "u:Mang Song's Lesson (archon staff)", kr: "망 송의 레슨", en: "Mang Song's Lesson", cat: "unique", base: "archon staff" },
  { id: "u:Viperfork (war fork)", kr: "바이퍼포크", en: "Viperfork", cat: "unique", base: "war fork" },
  { id: "u:Ethereal Edge (silver-edged axe)", kr: "에테리얼 엣지", en: "Ethereal Edge", cat: "unique", base: "silver-edged axe" },
  { id: "u:Demonhorn's Edge (destroyer helm)", kr: "데몬혼스 엣지", en: "Demonhorn's Edge", cat: "unique", base: "destroyer helm" },
  { id: "u:The Reaper's Toll (thresher)", kr: "리퍼스 톨", en: "The Reaper's Toll", cat: "unique", base: "thresher" },
  { id: "u:Spiritkeeper (earth spirit)", kr: "스피리트 키퍼", en: "Spiritkeeper", cat: "unique", base: "earth spirit" },
  { id: "u:Hellrack (colossus crossbow)", kr: "헬랙", en: "Hellrack", cat: "unique", base: "colossus crossbow" },
  { id: "u:Alma Negra (sacred rondache)", kr: "알마 네그라", en: "Alma Negra", cat: "unique", base: "sacred rondache" },
  { id: "u:Darkforge Spawn (bloodlord skull)", kr: "타크포스 스폰", en: "Darkforge Spawn", cat: "unique", base: "bloodlord skull" },
  { id: "u:Widowmaker (ward bow)", kr: "위도우메이커", en: "Widowmaker", cat: "unique", base: "ward bow" },
  { id: "u:Bloodraven's Charge (matriarchal bow)", kr: "블러드 레이븐의 차지", en: "Bloodraven's Charge", cat: "unique", base: "matriarchal bow" },
  { id: "u:Ghostflame (legend spike)", kr: "고스트플레임", en: "Ghostflame", cat: "unique", base: "legend spike" },
  { id: "u:Shadowkiller (battle cestus)", kr: "쉐도우 킬러", en: "Shadowkiller", cat: "unique", base: "battle cestus" },
  { id: "u:Gimmershred (flying axe)", kr: "김머쉬레드", en: "Gimmershred", cat: "unique", base: "flying axe" },
  { id: "u:Griffon's Eye (diadem)", kr: "그리폰의 아이", en: "Griffon's Eye", cat: "unique", base: "diadem" },
  { id: "u:Windhammer (ogre maul)", kr: "윈드해머", en: "Windhammer", cat: "unique", base: "ogre maul" },
  { id: "u:Thunderstroke (matriarchal javelin)", kr: "선더스트로크", en: "Thunderstroke", cat: "unique", base: "matriarchal javelin" },
  { id: "u:Demon's Arch (balrog spear)", kr: "데몬스 아치", en: "Demon's Arch", cat: "unique", base: "balrog spear" },
  { id: "u:Boneflame (succubae skull)", kr: "본플레임", en: "Boneflame", cat: "unique", base: "succubae skull" },
  { id: "u:Steelpillar (war pike)", kr: "스틸 필라", en: "Steelpillar", cat: "unique", base: "war pike" },
  { id: "u:Nightwing's Veil (spired helm)", kr: "나이트윙의 베일", en: "Nightwing's Veil", cat: "unique", base: "spired helm" },
  { id: "u:Crown of Ages (corona)", kr: "크라운 오브 에이지스", en: "Crown of Ages", cat: "unique", base: "corona" },
  { id: "u:Andariel's Visage (demonhead)", kr: "안다리엘의 비지스", en: "Andariel's Visage", cat: "unique", base: "demonhead" },
  { id: "u:Dragonscale (zakarum shield)", kr: "드래곤스케일", en: "Dragonscale", cat: "unique", base: "zakarum shield" },
  { id: "u:Steel Carapice (shadow plate)", kr: "스틸 캐러패이스", en: "Steel Carapice", cat: "unique", base: "shadow plate" },
  { id: "u:Medusa's Gaze (aegis)", kr: "메두사의 게이즈", en: "Medusa's Gaze", cat: "unique", base: "aegis" },
  { id: "u:Ravenlore (sky spirit)", kr: "레이븐로어", en: "Ravenlore", cat: "unique", base: "sky spirit" },
  { id: "u:Boneshade (lich wand)", kr: "본쉐이드", en: "Boneshade", cat: "unique", base: "lich wand" },
  { id: "u:Flamebellow (balrog blade)", kr: "플레임벨로우", en: "Flamebellow", cat: "unique", base: "balrog blade" },
  { id: "u:Fathom (dimensional shard)", kr: "데쓰 패썸", en: "Fathom", cat: "unique", base: "dimensional shard" },
  { id: "u:Wolfhowl (fury visor)", kr: "울프하울", en: "Wolfhowl", cat: "unique", base: "fury visor" },
  { id: "u:Spirit Ward (ward)", kr: "스피리트 워드", en: "Spirit Ward", cat: "unique", base: "ward" },
  { id: "u:Kira's Guardian (tiara)", kr: "기라의 가디안", en: "Kira's Guardian", cat: "unique", base: "tiara" },
  { id: "u:Ormus' Robes (dusk shroud)", kr: "오르무스 로브", en: "Ormus' Robes", cat: "unique", base: "dusk shroud" },
  { id: "u:Gheed's Fortune (charm)", kr: "기드의 포츈", en: "Gheed's Fortune", cat: "unique", base: "charm" },
  { id: "u:Stormlash (scourge)", kr: "스톰래쉬", en: "Stormlash", cat: "unique", base: "scourge" },
  { id: "u:Halaberd's Reign (conqueror crown)", kr: "할라버드의 레인", en: "Halaberd's Reign", cat: "unique", base: "conqueror crown" },
  { id: "u:Spike Thorn (blade barrier)", kr: "스파이크 쏜", en: "Spike Thorn", cat: "unique", base: "blade barrier" },
  { id: "u:Dracul's Grasp (vampirebone gloves)", kr: "드라큘의 그래스프", en: "Dracul's Grasp", cat: "unique", base: "vampirebone gloves" },
  { id: "u:Frostwind (cryptic sword)", kr: "프로스트윈드", en: "Frostwind", cat: "unique", base: "cryptic sword" },
  { id: "u:Templar's Might (sacred armor)", kr: "템플러의 마이트", en: "Templar's Might", cat: "unique", base: "sacred armor" },
  { id: "u:Eschuta's temper (eldritch orb)", kr: "에슈타스 템퍼", en: "Eschuta's temper", cat: "unique", base: "eldritch orb" },
  { id: "u:Firelizard's Talons (feral claws)", kr: "파이어리저드의 탤런스", en: "Firelizard's Talons", cat: "unique", base: "feral claws" },
  { id: "u:Sandstorm Trek (scarabshell boots)", kr: "샌드스톰 트랙", en: "Sandstorm Trek", cat: "unique", base: "scarabshell boots" },
  { id: "u:Marrowwalk (boneweave boots)", kr: "메로우워커", en: "Marrowwalk", cat: "unique", base: "boneweave boots" },
  { id: "u:Heaven's Light (mighty scepter)", kr: "헤븐의 라이트", en: "Heaven's Light", cat: "unique", base: "mighty scepter" },
  { id: "u:Arachnid Mesh (spiderweb sash)", kr: "아라크니드 메쉬", en: "Arachnid Mesh", cat: "unique", base: "spiderweb sash" },
  { id: "u:Nosferatu's Coil (vampirefang belt)", kr: "노스페라투의 코일", en: "Nosferatu's Coil", cat: "unique", base: "vampirefang belt" },
  { id: "u:Metalgrid (amulet)", kr: "메탈그리드", en: "Metalgrid", cat: "unique", base: "amulet" },
  { id: "u:Verdugo's Hearty Cord (mithril coil)", kr: "베르던고의 하티 코드", en: "Verdugo's Hearty Cord", cat: "unique", base: "mithril coil" },
  { id: "u:Carrion Wind (ring)", kr: "캐리언 윈드", en: "Carrion Wind", cat: "unique", base: "ring" },
  { id: "u:Giantskull (bone visage)", kr: "자이언트 스컬", en: "Giantskull", cat: "unique", base: "bone visage" },
  { id: "u:Ironward (caduceus)", kr: "애스트리언의 아이언 워드", en: "Ironward", cat: "unique", base: "caduceus" },
  { id: "u:Annihilus (charm)", kr: "애니힐러스", en: "Annihilus", cat: "unique", base: "charm" },
  { id: "u:Arioc's Needle (hyperion spear)", kr: "아리어의 니들", en: "Arioc's Needle", cat: "unique", base: "hyperion spear" },
  { id: "u:Cranebeak (war spike)", kr: "크레인비크", en: "Cranebeak", cat: "unique", base: "war spike" },
  { id: "u:Nord's Tenderizer (truncheon)", kr: "노드의 텐더라이저", en: "Nord's Tenderizer", cat: "unique", base: "truncheon" },
  { id: "u:Earthshifter (thunder maul)", kr: "어스 쉬프터", en: "Earthshifter", cat: "unique", base: "thunder maul" },
  { id: "u:Wraithflight (ghost glaive)", kr: "레이쓰 플라이트", en: "Wraithflight", cat: "unique", base: "ghost glaive" },
  { id: "u:Bonehew (ogre axe)", kr: "본휴", en: "Bonehew", cat: "unique", base: "ogre axe" },
  { id: "u:Ondal's Wisdom (elder staff)", kr: "온달의 지혜", en: "Ondal's Wisdom", cat: "unique", base: "elder staff" },
  { id: "u:The Reedeemer (mighty scepter)", kr: "리디머르", en: "The Reedeemer", cat: "unique", base: "mighty scepter" },
  { id: "u:Headhunter's Glory (troll nest)", kr: "헤드 헌터의 글로리", en: "Headhunter's Glory", cat: "unique", base: "troll nest" },
  { id: "u:Steelrend (ogre gauntlets)", kr: "스틸렌드", en: "Steelrend", cat: "unique", base: "ogre gauntlets" },
  { id: "u:Rainbow Facet (jewel, ltng/death)", kr: "레인보우 패시트 (번개 · 사망 시)", en: "Rainbow Facet", cat: "unique", base: "jewel" },
  { id: "u:Rainbow Facet (jewel, cold/death)", kr: "레인보우 패시트 (냉기 · 사망 시)", en: "Rainbow Facet", cat: "unique", base: "jewel" },
  { id: "u:Rainbow Facet (jewel, fire/death)", kr: "레인보우 패시트 (화염 · 사망 시)", en: "Rainbow Facet", cat: "unique", base: "jewel" },
  { id: "u:Rainbow Facet (jewel, pois/death)", kr: "레인보우 패시트 (독 · 사망 시)", en: "Rainbow Facet", cat: "unique", base: "jewel" },
  { id: "u:Rainbow Facet (jewel, ltng/levelup)", kr: "레인보우 패시트 (번개 · 레벨업 시)", en: "Rainbow Facet", cat: "unique", base: "jewel" },
  { id: "u:Rainbow Facet (jewel, cold/levelup)", kr: "레인보우 패시트 (냉기 · 레벨업 시)", en: "Rainbow Facet", cat: "unique", base: "jewel" },
  { id: "u:Rainbow Facet (jewel, fire/levelup)", kr: "레인보우 패시트 (화염 · 레벨업 시)", en: "Rainbow Facet", cat: "unique", base: "jewel" },
  { id: "u:Rainbow Facet (jewel, pois/levelup)", kr: "레인보우 패시트 (독 · 레벨업 시)", en: "Rainbow Facet", cat: "unique", base: "jewel" },
  { id: "u:Hellfire Torch (charm)", kr: "지옥의 횃불", en: "Hellfire Torch", cat: "unique", base: "charm" },
  { id: "s:Aldur's Watchtower/Aldur's Advance", kr: "알더의 어드벤스", en: "Aldur's Advance", cat: "set", setName: "알더의 와치타워" },
  { id: "s:Aldur's Watchtower/Aldur's Deception", kr: "알더의 디셉션", en: "Aldur's Deception", cat: "set", setName: "알더의 와치타워" },
  { id: "s:Aldur's Watchtower/Aldur's Gauntlet", kr: "알더의 리듬", en: "Aldur's Gauntlet", cat: "set", setName: "알더의 와치타워" },
  { id: "s:Aldur's Watchtower/Aldur's Stony Gaze", kr: "알더의 스토니 게이즈", en: "Aldur's Stony Gaze", cat: "set", setName: "알더의 와치타워" },
  { id: "s:Angelical Raiment/Angelic Halo", kr: "엔젤릭 헤일로우", en: "Angelic Halo", cat: "set", setName: "엔젤릭 레이먼트" },
  { id: "s:Angelical Raiment/Angelic Mantle", kr: "엔젤릭 맨틀", en: "Angelic Mantle", cat: "set", setName: "엔젤릭 레이먼트" },
  { id: "s:Angelical Raiment/Angelic Sickle", kr: "엔젤릭 시클", en: "Angelic Sickle", cat: "set", setName: "엔젤릭 레이먼트" },
  { id: "s:Angelical Raiment/Angelic Wings", kr: "엔젤릭 윙", en: "Angelic Wings", cat: "set", setName: "엔젤릭 레이먼트" },
  { id: "s:Arcanna's Tricks/Arcanna's Deathwand", kr: "아칸나의 데쓰원드", en: "Arcanna's Deathwand", cat: "set", setName: "아칸나 트릭스" },
  { id: "s:Arcanna's Tricks/Arcanna's Flesh", kr: "아칸나의 플레쉬", en: "Arcanna's Flesh", cat: "set", setName: "아칸나 트릭스" },
  { id: "s:Arcanna's Tricks/Arcanna's Head", kr: "아칸나의 헤드", en: "Arcanna's Head", cat: "set", setName: "아칸나 트릭스" },
  { id: "s:Arcanna's Tricks/Arcanna's Sign", kr: "아칸나의 싸인", en: "Arcanna's Sign", cat: "set", setName: "아칸나 트릭스" },
  { id: "s:Arctic Gear/Arctic Binding", kr: "아틱 바인딩", en: "Arctic Binding", cat: "set", setName: "아틱 기어" },
  { id: "s:Arctic Gear/Arctic Furs", kr: "아틱 퍼스", en: "Arctic Furs", cat: "set", setName: "아틱 기어" },
  { id: "s:Arctic Gear/Arctic Horn", kr: "아틱 혼", en: "Arctic Horn", cat: "set", setName: "아틱 기어" },
  { id: "s:Arctic Gear/Arctic Mitts", kr: "아틱 미트", en: "Arctic Mitts", cat: "set", setName: "아틱 기어" },
  { id: "s:Berserker's Garb/Berserker's Hatchet", kr: "버서커의 헤칫", en: "Berserker's Hatchet", cat: "set", setName: "버서커 아스널" },
  { id: "s:Berserker's Garb/Berserker's Hauberk", kr: "버서커의 허버크", en: "Berserker's Hauberk", cat: "set", setName: "버서커 아스널" },
  { id: "s:Berserker's Garb/Berserker's Headgear", kr: "버서커의 헤드기어", en: "Berserker's Headgear", cat: "set", setName: "버서커 아스널" },
  { id: "s:Bul-Kathos' Children/Bul-Kathos' Sacred Charge", kr: "발카서스의 세이크리드 차지", en: "Bul-Kathos' Sacred Charge", cat: "set", setName: "발카서스의 칠드런" },
  { id: "s:Bul-Kathos' Children/Bul-Kathos' Tribal Guardian", kr: "발카서스의 트라이벌 가디안", en: "Bul-Kathos' Tribal Guardian", cat: "set", setName: "발카서스의 칠드런" },
  { id: "s:Cathan's Traps/Cathan's Mesh", kr: "캐산의 메쉬", en: "Cathan's Mesh", cat: "set", setName: "캐산 트랩" },
  { id: "s:Cathan's Traps/Cathan's Rule", kr: "캐산의 룰", en: "Cathan's Rule", cat: "set", setName: "캐산 트랩" },
  { id: "s:Cathan's Traps/Cathan's Seal", kr: "캐산의 씨일", en: "Cathan's Seal", cat: "set", setName: "캐산 트랩" },
  { id: "s:Cathan's Traps/Cathan's Sigil", kr: "캐산의 씨질", en: "Cathan's Sigil", cat: "set", setName: "캐산 트랩" },
  { id: "s:Cathan's Traps/Cathan's Visage", kr: "캐산의 비지즈", en: "Cathan's Visage", cat: "set", setName: "캐산 트랩" },
  { id: "s:Civerb's Vestments/Civerb's Cudgel", kr: "시버브의 커질", en: "Civerb's Cudgel", cat: "set", setName: "시버브 베스트먼트" },
  { id: "s:Civerb's Vestments/Civerb's Icon", kr: "시버브의 아이콘", en: "Civerb's Icon", cat: "set", setName: "시버브 베스트먼트" },
  { id: "s:Civerb's Vestments/Civerb's Ward", kr: "시버브의 워드", en: "Civerb's Ward", cat: "set", setName: "시버브 베스트먼트" },
  { id: "s:Cleglaw's Brace/Cleglaw's Claw", kr: "클레그로우의 클러", en: "Cleglaw's Claw", cat: "set", setName: "클레글로우 브레이스" },
  { id: "s:Cleglaw's Brace/Cleglaw's Pincers", kr: "클레그로우의 핀서즈", en: "Cleglaw's Pincers", cat: "set", setName: "클레글로우 브레이스" },
  { id: "s:Cleglaw's Brace/Cleglaw's Tooth", kr: "클레그로우의 투쓰", en: "Cleglaw's Tooth", cat: "set", setName: "클레글로우 브레이스" },
  { id: "s:Cow King's Leathers/Cow King's Hide", kr: "카우 킹의 하이드", en: "Cow King's Hide", cat: "set", setName: "카우 킹의 레더" },
  { id: "s:Cow King's Leathers/Cow King's Hoofs", kr: "카우 킹의 후브", en: "Cow King's Hoofs", cat: "set", setName: "카우 킹의 레더" },
  { id: "s:Cow King's Leathers/Cow King's Horns", kr: "카우 킹의 혼스", en: "Cow King's Horns", cat: "set", setName: "카우 킹의 레더" },
  { id: "s:The Disciple/Credendum", kr: "크리덴덤", en: "Credendum", cat: "set", setName: "디싸이플" },
  { id: "s:Heaven's Brethren/Dangoon's Teaching", kr: "단군의 가르침", en: "Dangoon's Teaching", cat: "set", setName: "천인의 형제" },
  { id: "s:Death's Disguise/Death's Guard", kr: "데쓰 가드", en: "Death's Guard", cat: "set", setName: "데쓰 디스가이즈" },
  { id: "s:Death's Disguise/Death's Hand", kr: "데쓰 핸드", en: "Death's Hand", cat: "set", setName: "데쓰 디스가이즈" },
  { id: "s:Death's Disguise/Death's Touch", kr: "데쓰 터치", en: "Death's Touch", cat: "set", setName: "데쓰 디스가이즈" },
  { id: "s:Griswold's Legacy/Griswold's Heart", kr: "그리스월드의 하트", en: "Griswold's Heart", cat: "set", setName: "그리스월드의 리가시" },
  { id: "s:Griswold's Legacy/Griswold's Honor", kr: "그리스월드의 아너", en: "Griswold's Honor", cat: "set", setName: "그리스월드의 리가시" },
  { id: "s:Griswold's Legacy/Griswold's Valor", kr: "그리스월드의 밸러", en: "Griswold's Valor", cat: "set", setName: "그리스월드의 리가시" },
  { id: "s:Griswold's Legacy/Griswolds's Redemption", kr: "그리스월드의 리뎀프션", en: "Griswolds's Redemption", cat: "set", setName: "그리스월드의 리가시" },
  { id: "s:Orphan's Call/Guillaume's Face", kr: "길리엄의 페이스", en: "Guillaume's Face", cat: "set", setName: "오펀의 콜" },
  { id: "s:Heaven's Brethren/Haemosu's Adament", kr: "해모수의 강직", en: "Haemosu's Adament", cat: "set", setName: "천인의 형제" },
  { id: "s:Heaven's Brethren/Heaven's Taebaek", kr: "태백의 영광", en: "Heaven's Taebaek", cat: "set", setName: "천인의 형제" },
  { id: "s:Hsarus' Defense/Hsarus' Iron Fist", kr: "사루의 아이언 피스트", en: "Hsarus' Iron Fist", cat: "set", setName: "사루의 디펜스" },
  { id: "s:Hsarus' Defense/Hsarus' Iron Heel", kr: "사루의 아이언 힐", en: "Hsarus' Iron Heel", cat: "set", setName: "사루의 디펜스" },
  { id: "s:Hsarus' Defense/Hsarus' Iron Stay", kr: "사루의 아이언 스테이", en: "Hsarus' Iron Stay", cat: "set", setName: "사루의 디펜스" },
  { id: "s:Hwanin's Majesty/Hwanin's Justice", kr: "한인의 정의", en: "Hwanin's Justice", cat: "set", setName: "한인의 위엄" },
  { id: "s:Hwanin's Majesty/Hwanin's Refuge", kr: "한인의 보호", en: "Hwanin's Refuge", cat: "set", setName: "한인의 위엄" },
  { id: "s:Hwanin's Majesty/Hwanin's Seal", kr: "한인의 축복", en: "Hwanin's Seal", cat: "set", setName: "한인의 위엄" },
  { id: "s:Hwanin's Majesty/Hwanin's Splendor", kr: "한인의 광채", en: "Hwanin's Splendor", cat: "set", setName: "한인의 위엄" },
  { id: "s:Immortal King/Immortal King's Detail", kr: "임모틀 킹의 디테일", en: "Immortal King's Detail", cat: "set", setName: "임모틀 킹" },
  { id: "s:Immortal King/Immortal King's Forge", kr: "임모틀 킹의 포지", en: "Immortal King's Forge", cat: "set", setName: "임모틀 킹" },
  { id: "s:Immortal King/Immortal King's Pillar", kr: "임모틀 킹의 필라", en: "Immortal King's Pillar", cat: "set", setName: "임모틀 킹" },
  { id: "s:Immortal King/Immortal King's Soul Cage", kr: "임모틀 킹의 소울 케이지", en: "Immortal King's Soul Cage", cat: "set", setName: "임모틀 킹" },
  { id: "s:Immortal King/Immortal King's Stone Crusher", kr: "임모틀 킹의 스톤 크러셔", en: "Immortal King's Stone Crusher", cat: "set", setName: "임모틀 킹" },
  { id: "s:Immortal King/Immortal King's Will", kr: "임모틀 킹의 윌", en: "Immortal King's Will", cat: "set", setName: "임모틀 킹" },
  { id: "s:Infernal Tools/Infernal Cranium", kr: "인퍼널 크래니엄", en: "Infernal Cranium", cat: "set", setName: "인퍼널 툴스" },
  { id: "s:Infernal Tools/Infernal Sign", kr: "인퍼널 싸인", en: "Infernal Sign", cat: "set", setName: "인퍼널 툴스" },
  { id: "s:Infernal Tools/Infernal Torch", kr: "인퍼널 토치", en: "Infernal Torch", cat: "set", setName: "인퍼널 툴스" },
  { id: "s:Iratha's Finery/Iratha's Coil", kr: "이라사의 코일", en: "Iratha's Coil", cat: "set", setName: "이라사 파이너리" },
  { id: "s:Iratha's Finery/Iratha's Collar", kr: "이라사의 칼러", en: "Iratha's Collar", cat: "set", setName: "이라사 파이너리" },
  { id: "s:Iratha's Finery/Iratha's Cord", kr: "이라사의 코드", en: "Iratha's Cord", cat: "set", setName: "이라사 파이너리" },
  { id: "s:Iratha's Finery/Iratha's Cuff", kr: "이라사의 커프", en: "Iratha's Cuff", cat: "set", setName: "이라사 파이너리" },
  { id: "s:Isenhart's Armory/Isenhart's Case", kr: "아이젠하트의 케이스", en: "Isenhart's Case", cat: "set", setName: "아이젠하트 아머리" },
  { id: "s:Isenhart's Armory/Isenhart's Horns", kr: "아이젠하트의 혼즈", en: "Isenhart's Horns", cat: "set", setName: "아이젠하트 아머리" },
  { id: "s:Isenhart's Armory/Isenhart's Lightbrand", kr: "아이젠하트의 라이트브랜드", en: "Isenhart's Lightbrand", cat: "set", setName: "아이젠하트 아머리" },
  { id: "s:Isenhart's Armory/Isenhart's Parry", kr: "아이젠하트의 패리", en: "Isenhart's Parry", cat: "set", setName: "아이젠하트 아머리" },
  { id: "s:The Disciple/Laying of Hands", kr: "레잉 오브 핸즈", en: "Laying of Hands", cat: "set", setName: "디싸이플" },
  { id: "s:M'avina's Battle Hymn/M'avina's Caster", kr: "마비나의 캐스터", en: "M'avina's Caster", cat: "set", setName: "마비나의 배틀 힘" },
  { id: "s:M'avina's Battle Hymn/M'avina's Embrace", kr: "마비나의 엠브레스", en: "M'avina's Embrace", cat: "set", setName: "마비나의 배틀 힘" },
  { id: "s:M'avina's Battle Hymn/M'avina's Icy Clutch", kr: "마비나의 아이시 클러쳐", en: "M'avina's Icy Clutch", cat: "set", setName: "마비나의 배틀 힘" },
  { id: "s:M'avina's Battle Hymn/M'avina's Tenet", kr: "마비나의 테너트", en: "M'avina's Tenet", cat: "set", setName: "마비나의 배틀 힘" },
  { id: "s:M'avina's Battle Hymn/M'avina's True Sight", kr: "마비나의 트루 사이트", en: "M'avina's True Sight", cat: "set", setName: "마비나의 배틀 힘" },
  { id: "s:Orphan's Call/Magnus' Skin", kr: "메이그너스의 스킨", en: "Magnus' Skin", cat: "set", setName: "오펀의 콜" },
  { id: "s:McAuley's Folly/McAuley's Paragon", kr: "샌더의 파라곤", en: "McAuley's Paragon", cat: "set", setName: "샌더의 폴리" },
  { id: "s:McAuley's Folly/McAuley's Riprap", kr: "샌더의 립랩", en: "McAuley's Riprap", cat: "set", setName: "샌더의 폴리" },
  { id: "s:McAuley's Folly/McAuley's Superstition", kr: "샌더의 수퍼스티션", en: "McAuley's Superstition", cat: "set", setName: "샌더의 폴리" },
  { id: "s:McAuley's Folly/McAuley's Taboo", kr: "샌더의 타부", en: "McAuley's Taboo", cat: "set", setName: "샌더의 폴리" },
  { id: "s:Milabrega's Regalia/Milabrega's Diadem", kr: "밀라브레가의 다이어뎀", en: "Milabrega's Diadem", cat: "set", setName: "밀라브레가 리게일리어" },
  { id: "s:Milabrega's Regalia/Milabrega's Orb", kr: "밀라브레가의 오브", en: "Milabrega's Orb", cat: "set", setName: "밀라브레가 리게일리어" },
  { id: "s:Milabrega's Regalia/Milabrega's Robe", kr: "밀라브레가의 로브", en: "Milabrega's Robe", cat: "set", setName: "밀라브레가 리게일리어" },
  { id: "s:Milabrega's Regalia/Milabrega's Rod", kr: "밀라브레가의 로드", en: "Milabrega's Rod", cat: "set", setName: "밀라브레가 리게일리어" },
  { id: "s:Naj's Ancient Set/Naj's Circlet", kr: "나즈 서클리트", en: "Naj's Circlet", cat: "set", setName: "나즈 앤션트 베스티지" },
  { id: "s:Naj's Ancient Set/Naj's Light Plate", kr: "나즈 라이트 플레이트", en: "Naj's Light Plate", cat: "set", setName: "나즈 앤션트 베스티지" },
  { id: "s:Naj's Ancient Set/Naj's Puzzler", kr: "나즈 퍼즐", en: "Naj's Puzzler", cat: "set", setName: "나즈 앤션트 베스티지" },
  { id: "s:Natalya's Odium/Natalya's Mark", kr: "나탈리아의 마크", en: "Natalya's Mark", cat: "set", setName: "나탈리아의 오디엄" },
  { id: "s:Natalya's Odium/Natalya's Shadow", kr: "나탈리아의 쉐도우", en: "Natalya's Shadow", cat: "set", setName: "나탈리아의 오디엄" },
  { id: "s:Natalya's Odium/Natalya's Soul", kr: "나탈리아의 소울", en: "Natalya's Soul", cat: "set", setName: "나탈리아의 오디엄" },
  { id: "s:Natalya's Odium/Natalya's Totem", kr: "나탈리아의 토템", en: "Natalya's Totem", cat: "set", setName: "나탈리아의 오디엄" },
  { id: "s:Heaven's Brethren/Ondal's Almighty", kr: "온달의 사랑", en: "Ondal's Almighty", cat: "set", setName: "천인의 형제" },
  { id: "s:The Disciple/Rite of Passage", kr: "고대인의 통과의례", en: "Rite of Passage", cat: "set", setName: "디싸이플" },
  { id: "s:Sazabi's Grand Tribute/Sazabi's Cobalt Redeemer", kr: "사자바이의 코발트 리디머르", en: "Sazabi's Cobalt Redeemer", cat: "set", setName: "사자바이의 그랜드 트라이뷰트" },
  { id: "s:Sazabi's Grand Tribute/Sazabi's Ghost Liberator", kr: "사자바이의 고스트 리버레이터", en: "Sazabi's Ghost Liberator", cat: "set", setName: "사자바이의 그랜드 트라이뷰트" },
  { id: "s:Sazabi's Grand Tribute/Sazabi's Mental Sheath", kr: "사자바이의 멘틀 쉬쓰", en: "Sazabi's Mental Sheath", cat: "set", setName: "사자바이의 그랜드 트라이뷰트" },
  { id: "s:Sigon's Complete Steel/Sigon's Gage", kr: "사이곤의 게이지", en: "Sigon's Gage", cat: "set", setName: "사이곤 컴플릿스틸" },
  { id: "s:Sigon's Complete Steel/Sigon's Guard", kr: "사이곤의 가드", en: "Sigon's Guard", cat: "set", setName: "사이곤 컴플릿스틸" },
  { id: "s:Sigon's Complete Steel/Sigon's Sabot", kr: "사이곤의 새보우", en: "Sigon's Sabot", cat: "set", setName: "사이곤 컴플릿스틸" },
  { id: "s:Sigon's Complete Steel/Sigon's Shelter", kr: "사이곤의 쉘터", en: "Sigon's Shelter", cat: "set", setName: "사이곤 컴플릿스틸" },
  { id: "s:Sigon's Complete Steel/Sigon's Visor", kr: "사이곤의 바이저", en: "Sigon's Visor", cat: "set", setName: "사이곤 컴플릿스틸" },
  { id: "s:Sigon's Complete Steel/Sigon's Wrap", kr: "사이곤의 랩", en: "Sigon's Wrap", cat: "set", setName: "사이곤 컴플릿스틸" },
  { id: "s:The Disciple/Spiritual Custodian", kr: "다크 애드히어런트", en: "Spiritual Custodian", cat: "set", setName: "디싸이플" },
  { id: "s:Tal Rasha's Wrappings/Tal Rasha's Adjudication", kr: "탈 라샤의 어쥬디케이션", en: "Tal Rasha's Adjudication", cat: "set", setName: "탈 라샤의 래핑스" },
  { id: "s:Tal Rasha's Wrappings/Tal Rasha's Fire-Spun Cloth", kr: "탈 라샤의 파인-스펀 클로쓰", en: "Tal Rasha's Fire-Spun Cloth", cat: "set", setName: "탈 라샤의 래핑스" },
  { id: "s:Tal Rasha's Wrappings/Tal Rasha's Horadric Crest", kr: "탈 라샤의 호라드릭 크레스트", en: "Tal Rasha's Horadric Crest", cat: "set", setName: "탈 라샤의 래핑스" },
  { id: "s:Tal Rasha's Wrappings/Tal Rasha's Howling Wind", kr: "탈 라샤의 가이언쉽", en: "Tal Rasha's Howling Wind", cat: "set", setName: "탈 라샤의 래핑스" },
  { id: "s:Tal Rasha's Wrappings/Tal Rasha's Lidless Eye", kr: "탈 라샤의 리드리스 아이", en: "Tal Rasha's Lidless Eye", cat: "set", setName: "탈 라샤의 래핑스" },
  { id: "s:Tancred's Battlegear/Tancred's Crowbill", kr: "탄크레드의 크로우빌", en: "Tancred's Crowbill", cat: "set", setName: "탄크레드 배틀기어" },
  { id: "s:Tancred's Battlegear/Tancred's Hobnails", kr: "탄크레드의 헙네일즈", en: "Tancred's Hobnails", cat: "set", setName: "탄크레드 배틀기어" },
  { id: "s:Tancred's Battlegear/Tancred's Skull", kr: "탄크레드의 스컬", en: "Tancred's Skull", cat: "set", setName: "탄크레드 배틀기어" },
  { id: "s:Tancred's Battlegear/Tancred's Spine", kr: "탄크레드의 스파인", en: "Tancred's Spine", cat: "set", setName: "탄크레드 배틀기어" },
  { id: "s:Tancred's Battlegear/Tancred's Weird", kr: "탄크레드의 와이어드", en: "Tancred's Weird", cat: "set", setName: "탄크레드 배틀기어" },
  { id: "s:The Disciple/Telling of Beads", kr: "텔링 오브 비드", en: "Telling of Beads", cat: "set", setName: "디싸이플" },
  { id: "s:Trang-Oul's Avatar/Trang-Oul's Claws", kr: "트랑-울의 클러스", en: "Trang-Oul's Claws", cat: "set", setName: "트랑-울의 아바타" },
  { id: "s:Trang-Oul's Avatar/Trang-Oul's Girth", kr: "트랑-울의 거즈", en: "Trang-Oul's Girth", cat: "set", setName: "트랑-울의 아바타" },
  { id: "s:Trang-Oul's Avatar/Trang-Oul's Guise", kr: "트랑-울의 가이즈", en: "Trang-Oul's Guise", cat: "set", setName: "트랑-울의 아바타" },
  { id: "s:Trang-Oul's Avatar/Trang-Oul's Scales", kr: "트랑-울의 스케일스", en: "Trang-Oul's Scales", cat: "set", setName: "트랑-울의 아바타" },
  { id: "s:Trang-Oul's Avatar/Trang-Oul's Wing", kr: "트랑-울의 윙", en: "Trang-Oul's Wing", cat: "set", setName: "트랑-울의 아바타" },
  { id: "s:Vidala's Rig/Vidala's Ambush", kr: "비달라의 앰부쉬", en: "Vidala's Ambush", cat: "set", setName: "비달라 리그" },
  { id: "s:Vidala's Rig/Vidala's Barb", kr: "비달라의 바아브", en: "Vidala's Barb", cat: "set", setName: "비달라 리그" },
  { id: "s:Vidala's Rig/Vidala's Fetlock", kr: "비달라의 페트락", en: "Vidala's Fetlock", cat: "set", setName: "비달라 리그" },
  { id: "s:Vidala's Rig/Vidala's Snare", kr: "비달라의 스네어", en: "Vidala's Snare", cat: "set", setName: "비달라 리그" },
  { id: "s:Orphan's Call/Wihtstan's Guard", kr: "위트스탄의 가드", en: "Wihtstan's Guard", cat: "set", setName: "오펀의 콜" },
  { id: "s:Orphan's Call/Wilhelm's Pride", kr: "빌헬름의 프라이드", en: "Wilhelm's Pride", cat: "set", setName: "오펀의 콜" },
];
