// 신규 아이템 데이터(구 app/new-items/page.js에서 이동 — 값·순서·주석 무변경).
// new-items 페이지와 grail 트래커가 공유.
// cat: rw=룬워드, unique=고유, jewel=고유 주얼, set=세트, statue=고대인 조각상, charm=파괴 부적, base=마법서 베이스, misc=세계석 조각
export const ITEMS = [
  // ─── 룬워드 ───
  { kr: "권위", en: "Authority", cat: "rw", slug: "authority", meta: "룬워드 · Hel + Shael + Ral · 3소켓 갑옷", alias: "권위 룬워드" },
  { kr: "마녀단", en: "Coven", cat: "rw", slug: "coven", meta: "룬워드 · Ist + Ral + Io · 3소켓 투구", alias: "코븐 마녀회" },
  { kr: "공허", en: "Void", cat: "rw", slug: "void", meta: "룬워드 · Thul + Zod + Ist · 3소켓 단검", alias: "보이드" },
  { kr: "경계", en: "Vigilance", cat: "rw", slug: "vigilance", meta: "룬워드 · Dol + Gul · 2소켓 방패", alias: "비질런스" },
  { kr: "의식", en: "Ritual", cat: "rw", slug: "ritual", meta: "룬워드 · Amn + Shael + Ohm · 3소켓 단검", alias: "리추얼" },
  { kr: "광기", en: "Mania", cat: "rw", slug: "mania", meta: "룬워드 · Shael + Ko + Eld · 무기 (구 허슬 Hustle 무기 버전 개명)", alias: "마니아 허슬" },
  { kr: "히스테리아", en: "Hysteria", cat: "rw", slug: "hysteria", meta: "룬워드 · Shael + Ko + Eld · 갑옷 (구 허슬 Hustle 갑옷 버전 개명)", alias: "허슬" },
  // ─── 고유 아이템 ───
  { kr: "공포송곳니", en: "Dreadfang", cat: "unique", slug: "dreadfang", meta: "고유 검 · 레전드 소드(Legend Sword)", alias: "드레드팽 공포 송곳니" },
  { kr: "피의 맹약 파편", en: "Bloodpact Shard", cat: "unique", slug: "bloodpact-shard", meta: "고유 단검 · 미스릴 포인트(Mithril Point)", alias: "블러드팩트 샤드" },
  { kr: "지옥파수꾼의 의지", en: "Hellwarden's Will", cat: "unique", slug: "hellwardens-will", meta: "고유 투구 · 데스 마스크(Death Mask)", alias: "지옥 파수꾼의 의지 헬워든" },
  { kr: "망령걸음", en: "Wraithstep", cat: "unique", slug: "wraithstep", meta: "고유 장화 · 미러드 부츠(Mirrored Boots)", alias: "레이스스텝" },
  { kr: "기드의 내기", en: "Gheed's Wager", cat: "unique", slug: "gheeds-wager", meta: "고유 벨트 · 트롤 벨트(Troll Belt)", alias: "기드 웨이저" },
  { kr: "새총", en: "Sling", cat: "unique", slug: "sling", meta: "고유 반지 · 적 마법 저항 감소", alias: "슬링" },
  { kr: "오팔맥", en: "Opalvein", cat: "unique", slug: "opalvein", meta: "고유 반지 · 무작위 원소 피해 %", alias: "오팔베인" },
  { kr: "엔트로피 로켓", en: "Entropy Locket", cat: "unique", slug: "entropy-locket", meta: "고유 목걸이", alias: "앤트로피 로켓 엔트로피 목걸이" },
  { kr: "아르스 알디아볼로스", en: "Ars Al'Diabolos", cat: "unique", slug: "ars-aldiabolos", meta: "고유 마법서 · 신성모독 마법서(Blasphemous Grimoire) · 악마술사 전용", alias: "알 디아볼로스" },
  { kr: "아르스 토르바알로스", en: "Ars Tor'Baalos", cat: "unique", slug: "ars-torbaalos", meta: "고유 마법서 · 신성모독 전서(Blasphemous Compendium) · 악마술사 전용", alias: "토르 바알로스" },
  { kr: "아르스 둘메피스토스", en: "Ars Dul'Mephistos", cat: "unique", slug: "ars-dulmephistos", meta: "고유 마법서 · 비술 고서(Occult Tome) · 악마술사 전용", alias: "둘 메피스토스" },
  { kr: "신중한 진노", en: "Measured Wrath", cat: "unique", slug: "measured-wrath", meta: "고유 마법서 · 불탄 문헌(Burnt Text) · 악마술사 전용", alias: "메저드 라스" },
  // ─── 위압적인 고대인 조각상 (재료) ───
  { kr: "탈릭의 고뇌", en: "Talic's Anguish", cat: "statue", slug: "talics-anguish", meta: "위압적인 고대인 조각상 · 1막 공포 액트보스 드랍 · 5종 조합 시 붉은 차원문", alias: "탈릭 조각상 석상" },
  { kr: "콜릭의 고통", en: "Korlic's Pain", cat: "statue", slug: "korlics-pain", meta: "위압적인 고대인 조각상 · 2막 공포 액트보스 드랍 · 5종 조합 시 붉은 차원문", alias: "코를릭의 고통 콜릭 석상" },
  { kr: "마도크의 분노", en: "Madawc's Ire", cat: "statue", slug: "madawcs-ire", meta: "위압적인 고대인 조각상 · 3막 공포 액트보스 드랍 · 5종 조합 시 붉은 차원문", alias: "마도크 석상" },
  { kr: "불카토스의 악몽", en: "Bul-Kathos' Nightmare", cat: "statue", slug: "bul-kathos-nightmare", meta: "위압적인 고대인 조각상 · 4막 공포 액트보스 드랍 · 5종 조합 시 붉은 차원문", alias: "불카토스 석상" },
  { kr: "워러스크의 종말", en: "Worusk's End", cat: "statue", slug: "worusks-end", meta: "위압적인 고대인 조각상 · 5막 공포 액트보스 드랍 · 5종 조합 시 붉은 차원문", alias: "워러스크 석상" },
  // ─── 고유 주얼 (위압적인 고대인 보상) ───
  { kr: "수호자의 불", en: "Defender's Fire", cat: "jewel", slug: "defenders-fire", meta: "고유 주얼 · 위압적인 고대인(Colossal Ancients) 보상", alias: "디펜더" },
  { kr: "수호자의 역정", en: "Defender's Bile", cat: "jewel", slug: "defenders-bile", meta: "고유 주얼 · 위압적인 고대인 보상", alias: "디펜더 바일" },
  { kr: "보호자의 돌", en: "Protector's Stone", cat: "jewel", slug: "protectors-stone", meta: "고유 주얼 · 위압적인 고대인 보상", alias: "프로텍터" },
  { kr: "보호자의 서리", en: "Protector's Frost", cat: "jewel", slug: "protectors-frost", meta: "고유 주얼 · 위압적인 고대인 보상", alias: "프로텍터 프로스트" },
  { kr: "감시자의 빛", en: "Guardian's Light", cat: "jewel", slug: "guardians-light", meta: "고유 주얼 · 위압적인 고대인 보상", alias: "가디언 라이트" },
  { kr: "감시자의 천둥", en: "Guardian's Thunder", cat: "jewel", slug: "guardians-thunder", meta: "고유 주얼 · 위압적인 고대인 보상", alias: "가디언 썬더" },
  // ─── 세트 ───
  { kr: "재앙의 복장", en: "Bane's Garments", cat: "set", slug: null, meta: "세트명 (노말 · 3부위) — 아래 개별 부위로 거래", alias: "베인 세트" },
  { kr: "재앙의 맹약자", en: "Bane's Oathmaker", cat: "set", slug: "banes-oathmaker", meta: "세트 단검 · 크리스(Kris) · 재앙의 복장", alias: "베인 오스메이커" },
  { kr: "재앙의 망령껍질", en: "Bane's Wraithskin", cat: "set", slug: "banes-wraithskin", meta: "세트 갑옷 · 하드 레더 아머(Hard Leather Armor) · 재앙의 복장", alias: "베인 레이스스킨" },
  { kr: "재앙의 권위", en: "Bane's Authority", cat: "set", slug: "banes-authority", meta: "세트 벨트 · 라이트 벨트(Light Belt) · 재앙의 복장", alias: "베인" },
  { kr: "호라존의 광채", en: "Horazon's Splendor", cat: "set", slug: null, meta: "세트명 (엘리트 · 5부위 · 악마술사 전용) — 아래 개별 부위로 거래", alias: "호라존 세트" },
  { kr: "호라존의 표정", en: "Horazon's Countenance", cat: "set", slug: "horazons-countenance", meta: "세트 투구 · 데몬헤드(Demonhead) · 호라존의 광채", alias: "호라존 카운터넌스" },
  { kr: "호라존의 지배", en: "Horazon's Dominion", cat: "set", slug: "horazons-dominion", meta: "세트 갑옷 · 러셋 아머(Russet Armor) · 호라존의 광채", alias: "호라존 도미니언" },
  { kr: "호라존의 장악", en: "Horazon's Hold", cat: "set", slug: "horazons-hold", meta: "세트 장갑 · 데몬하이드 글러브(Demonhide Gloves) · 호라존의 광채", alias: "호라존 홀드" },
  { kr: "호라존의 유산", en: "Horazon's Legacy", cat: "set", slug: "horazons-legacy", meta: "세트 장화 · 미러드 부츠(Mirrored Boots) · 호라존의 광채", alias: "호라존 레거시" },
  { kr: "호라존의 비밀", en: "Horazon's Secrets", cat: "set", slug: "horazons-secrets", meta: "세트 마법서 · 비술 고문서(Occult Codex) · 호라존의 광채", alias: "호라존 시크릿" },
  // ─── 파괴 부적 (잠복하는 / 새로워진) ───
  { kr: "잠복하는 칠흑의 천공", en: "Latent Black Cleft", cat: "charm", slug: "latent-black-cleft", meta: "파괴 거대 부적(마법) · 공포의 영역 전령 드랍", alias: "잠복 칠흑" },
  { kr: "잠복하는 뼈의 분쇄", en: "Latent Bone Break", cat: "charm", slug: "latent-bone-break", meta: "파괴 거대 부적(물리) · 전령 드랍", alias: "잠복 뼈" },
  { kr: "잠복하는 추위의 파열", en: "Latent Cold Rupture", cat: "charm", slug: "latent-cold-rupture", meta: "파괴 거대 부적(냉기) · 전령 드랍", alias: "잠복 추위 냉기" },
  { kr: "잠복하는 천상의 틈", en: "Latent Crack of the Heavens", cat: "charm", slug: "latent-crack-of-the-heavens", meta: "파괴 거대 부적(번개) · 전령 드랍", alias: "잠복 천상" },
  { kr: "잠복하는 불길의 균열", en: "Latent Flame Rift", cat: "charm", slug: "latent-flame-rift", meta: "파괴 거대 부적(화염) · 전령 드랍", alias: "잠복 불길 화염" },
  { kr: "잠복하는 부패의 분열", en: "Latent Rotting Fissure", cat: "charm", slug: "latent-rotting-fissure", meta: "파괴 거대 부적(독) · 전령 드랍", alias: "잠복 부패 독" },
  { kr: "새로워진 칠흑의 천공", en: "Renewed Black Cleft", cat: "charm", slug: "renewed-black-cleft", meta: "파괴 거대 부적(마법) 강화판 · 호라드림 함 조합", alias: "리뉴드 칠흑" },
  { kr: "새로워진 뼈의 분쇄", en: "Renewed Bone Break", cat: "charm", slug: "renewed-bone-break", meta: "파괴 거대 부적(물리) 강화판 · 호라드림 함 조합", alias: "리뉴드 뼈" },
  { kr: "새로워진 추위의 파열", en: "Renewed Cold Rupture", cat: "charm", slug: "renewed-cold-rupture", meta: "파괴 거대 부적(냉기) 강화판 · 호라드림 함 조합", alias: "리뉴드 냉기" },
  { kr: "새로워진 천상의 틈", en: "Renewed Crack of the Heavens", cat: "charm", slug: "renewed-crack-of-the-heavens", meta: "파괴 거대 부적(번개) 강화판 · 호라드림 함 조합", alias: "리뉴드 천상" },
  { kr: "새로워진 불길의 균열", en: "Renewed Flame Rift", cat: "charm", slug: "renewed-flame-rift", meta: "파괴 거대 부적(화염) 강화판 · 호라드림 함 조합", alias: "리뉴드 화염" },
  { kr: "새로워진 부패의 분열", en: "Renewed Rotting Fissure", cat: "charm", slug: "renewed-rotting-fissure", meta: "파괴 거대 부적(독) 강화판 · 호라드림 함 조합", alias: "리뉴드 독" },
  // ─── 세계석 조각 ───
  { kr: "서부 세계석 조각", en: "Western Worldstone Shard", cat: "misc", slug: "western-worldstone-shard", meta: "소모품 · 공포의 영역 지정(1막)", alias: "월드스톤" },
  { kr: "동부 세계석 조각", en: "Eastern Worldstone Shard", cat: "misc", slug: "eastern-worldstone-shard", meta: "소모품 · 공포의 영역 지정(2막)", alias: "월드스톤" },
  { kr: "남부 세계석 조각", en: "Southern Worldstone Shard", cat: "misc", slug: "southern-worldstone-shard", meta: "소모품 · 공포의 영역 지정(3막)", alias: "월드스톤" },
  { kr: "깊은 세계석 조각", en: "Deep Worldstone Shard", cat: "misc", slug: "deep-worldstone-shard", meta: "소모품 · 공포의 영역 지정(4막)", alias: "심층 세계석 월드스톤" },
  { kr: "북부 세계석 조각", en: "Northern Worldstone Shard", cat: "misc", slug: "northern-worldstone-shard", meta: "소모품 · 공포의 영역 지정(5막)", alias: "월드스톤" },
  // ─── 마법서 베이스 (악마술사 전용 방패) ───
  { kr: "오래된 책", en: "Old Book", cat: "base", slug: "old-book", meta: "마법서 베이스 · 노말", alias: "낡은 책" },
  { kr: "고서", en: "Tome", cat: "base", slug: "tome", meta: "마법서 베이스 · 노말", alias: "톰" },
  { kr: "고문서", en: "Codex", cat: "base", slug: "codex", meta: "마법서 베이스 · 노말", alias: "코덱스" },
  { kr: "전서", en: "Compendium", cat: "base", slug: "compendium", meta: "마법서 베이스 · 노말", alias: "컴펜디움" },
  { kr: "마법서", en: "Grimoire", cat: "base", slug: "grimoire", meta: "마법서 베이스 · 노말", alias: "그리무아르" },
  { kr: "불탄 문헌", en: "Burnt Text", cat: "base", slug: "burnt-text", meta: "마법서 베이스 · 익셉셔널", alias: "번트 텍스트" },
  { kr: "어두운 고서", en: "Dark Tome", cat: "base", slug: "dark-tome", meta: "마법서 베이스 · 익셉셔널", alias: "다크 톰 암흑 고서" },
  { kr: "어두운 고문서", en: "Dark Codex", cat: "base", slug: "dark-codex", meta: "마법서 베이스 · 익셉셔널", alias: "다크 코덱스" },
  { kr: "빙의된 전서", en: "Possessed Compendium", cat: "base", slug: "possessed-compendium", meta: "마법서 베이스 · 익셉셔널", alias: "포제스드" },
  { kr: "빙의된 마법서", en: "Possessed Grimoire", cat: "base", slug: "possessed-grimoire", meta: "마법서 베이스 · 익셉셔널", alias: "포제스드 그리무아르" },
  { kr: "잊힌 책자", en: "Forgotten Volume", cat: "base", slug: "forgotten-volume", meta: "마법서 베이스 · 엘리트", alias: "잊혀진 책자 포가튼" },
  { kr: "비술 고서", en: "Occult Tome", cat: "base", slug: "occult-tome", meta: "마법서 베이스 · 엘리트", alias: "오컬트 톰" },
  { kr: "비술 고문서", en: "Occult Codex", cat: "base", slug: "occult-codex", meta: "마법서 베이스 · 엘리트", alias: "오컬트 코덱스" },
  { kr: "신성모독 전서", en: "Blasphemous Compendium", cat: "base", slug: "blasphemous-compendium", meta: "마법서 베이스 · 엘리트", alias: "블라스페머스" },
  { kr: "신성모독 마법서", en: "Blasphemous Grimoire", cat: "base", slug: "blasphemous-grimoire", meta: "마법서 베이스 · 엘리트", alias: "블라스페머스 그리무아르" },
];
